apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    app: oh-minecraft
spec:
  ports:
    - port: 25565
      name: game
    - port: 25575
      name: console
  clusterIP: None
  selector:
    app: oh-minecraft
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oh-minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oh-minecraft
  serviceName: "minecraft"
  template:
    metadata:
      labels:
        app: oh-minecraft
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: oh-minecraft
        image: openhack/minecraft-server:2.0
        resources:
          requests:
            cpu: 100m
            memory: 2Gi
          limits:
            cpu: 250m
            memory: 4Gi
        env:
          - name: EULA
            value: "TRUE"
        ports:
        - containerPort: 25565
          name: game
        - containerPort: 25575
          name: console
        volumeMounts:
        - mountPath: "/data"
          name: minecraft
  volumeClaimTemplates:
    - metadata:
        name: minecraft
      spec:
        storageClassName: default
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: oh-minecraft
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    name: game
  - port: 25575
    name: console
  selector:
    app: oh-minecraft
