apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    app: oh-minecraft
spec:
  ports:
    - port: 25565
      name: game
    - port: 25575
      name: console
  clusterIP: None
  selector:
    app: oh-minecraft
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oh-minecraft
  annotations:
    service-per-pod-label: "pod-name"
    service-per-pod-ports: "25565:25565"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oh-minecraft
  serviceName: "minecraft"
  template:
    metadata:
      labels:
        app: oh-minecraft
      annotations:
        pod-name-label: "pod-name"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: oh-minecraft
        image: openhack/minecraft-server:2.0
        resources:
          requests:
            cpu: 100m
            memory: 2Gi
          limits:
            cpu: 250m
            memory: 4Gi
        env:
          - name: EULA
            value: "TRUE"
        ports:
        - containerPort: 25565
          name: game
        - containerPort: 25575
          name: console
        volumeMounts:
        - mountPath: "/data"
          name: minecraft
  volumeClaimTemplates:
    - metadata:
        name: minecraft
      spec:
        storageClassName: default
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: minecraft
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: StatefulSet
    name: minecraft
  targetCPUUtilizationPercentage: 50

